* Advent of Code 2017
** Perl Version
*** DONE Day 1
#+begin_src perl :exports both
  BEGIN { unshift @INC, './src'; }
  use Day1;
  open my $fh, '<', 'inputs/day1'
    or die "Could not open file $!\n";
  chomp(my $str = <$fh>);
  [Day1::captcha2($str), Day1::captcha_half_way($str)];
#+end_src

#+RESULTS:
| 1047 |
|  982 |

The starting value bug was due to newline at the end of the input string.
*** Day 2
Simple ~mapreduce~ for an sequence of arrays.
#+begin_src perl :exports both
  BEGIN {unshift @INC, './src'}
  use Day2;
  [ Day2::crunch_spreadsheet('inputs/day2',
			     \&Day2::checksum,   # map for each line
			     sub {$_[0]+$_[1]}), # reduce with plus
    Day2::crunch_spreadsheet('inputs/day2',
			     \&Day2::checksum_div,
			     sub {$_[0] + $_[1]}),
  ]

#+end_src

#+RESULTS:
| 47623 |
|   312 |
If I assume that we need both the answers, the above method of iterating in the file might be inefficient.
In the context of correct method being part2, it might be a good solution.
** Agda Version
*** Day 1
 Even the basic IO is so convoluted that to run a hello world program it compiles 130 modules. There are a lot of utilities not defined here. I am trying to define a read-number function from a string. Haven't used this in the problem.

 Got stuck trying to destruct on equality of two characters.  By luck found out about ~Data.Char.≈?~ which is the decidable instance of character equality. So I have partly solved the first part of the problem. I did not compare the last and first characters of the input in the program, So I have checked it manually (and added 8) which gave me the correct answer.
    #+begin_src sh :exports results :results output verbatim
      cd src/
      ./day1
    #+end_src

    #+RESULTS:
    : 1039
    : 952

 Completed the second part too, using ~splitAt~ function and rotating the list in half. I am only tripping up at IO and using Coinduction with INFINITY, SHARP and FLAT constructors. Need more familiarity with all of these.
*** Day 2
 I need to get more familiar using generic abstractions. I keep writing small utilities which probably can be built simply using stdlib.

 #+begin_src sh :exports results :results output verbatim
   cd src/
   ./day2
 #+end_src

 #+RESULTS:
 : 47623
 : 312
